// Generated by CoffeeScript 1.3.3
(function() {

  window.HN = {
    Models: {},
    Collections: {},
    Views: {},
    Utils: {},
    init: function() {
      var originalSync;
      forge.logging.log("Init");
      forge.topbar.show();
      forge.topbar.setTitle("HN");
      forge.topbar.setTint([255, 102, 0, 255]);
      originalSync = Backbone.sync;
      Backbone.sync = function(method, model, options) {
        options = _.extend(options, {
          dataType: 'html',
          contentType: 'text/html',
          processData: false
        });
        return originalSync.apply(Backbone, [method, model, options]);
      };
      HN.news = new HN.Collections.News();
      return HN.news.fetch({
        success: function(collection, response) {
          HN.router = new HN.Router();
          return Backbone.history.start();
        }
      });
    }
  };

}).call(this);
