// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  HN.Router = (function(_super) {

    __extends(Router, _super);

    function Router() {
      return Router.__super__.constructor.apply(this, arguments);
    }

    Router.prototype.routes = {
      "": "news",
      "newest": "newest",
      "jobs": "jobs",
      "ask": "ask",
      "post/:id": "post",
      "user/:id": "user"
    };

    Router.prototype.news = function() {
      var news;
      HN.TabBarButtons.news.setActive();
      console.log("News");
      news = new HN.Views.News({
        collection: HN.news,
        back: false
      });
      return news.show();
    };

    Router.prototype.newest = function() {
      var newest;
      HN.TabBarButtons.newest.setActive();
      console.log("Newest");
      newest = new HN.Views.News({
        collection: HN.newest,
        back: false
      });
      return newest.show();
    };

    Router.prototype.jobs = function() {
      var jobs;
      HN.TabBarButtons.jobs.setActive();
      console.log("Jobs");
      jobs = new HN.Views.News({
        collection: HN.jobs,
        back: false
      });
      return jobs.show();
    };

    Router.prototype.ask = function() {
      var ask;
      HN.TabBarButtons.ask.setActive();
      console.log("ask");
      ask = new HN.Views.News({
        collection: HN.ask,
        back: false
      });
      return ask.show();
    };

    Router.prototype.post = function(id) {
      var model, post;
      console.log("Post - " + id);
      model = new HN.Models.Discussion({
        id: id
      });
      post = new HN.Views.Post({
        model: model,
        back: true
      });
      return post.show();
    };

    Router.prototype.user = function(id) {
      var model, user;
      console.log("User -" + id);
      model = new HN.Models.User({
        user: id
      });
      user = new HN.Views.User({
        model: model,
        back: true
      });
      return user.show();
    };

    return Router;

  })(Backbone.Router);

}).call(this);
