// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  HN.Router = (function(_super) {

    __extends(Router, _super);

    function Router() {
      return Router.__super__.constructor.apply(this, arguments);
    }

    Router.prototype.routes = {
      "": "news",
      "post/:id": "post"
    };

    Router.prototype.news = function() {
      var news;
      console.log("News");
      news = new HN.Views.News({
        collection: HN.news,
        back: false
      });
      return news.show();
    };

    Router.prototype.post = function(id) {
      var model, post;
      console.log("Post - " + id);
      model = new HN.Models.Discussion({
        id: id
      });
      post = new HN.Views.Post({
        model: model,
        back: true
      });
      return post.show();
    };

    return Router;

  })(Backbone.Router);

}).call(this);
