// Generated by CoffeeScript 1.3.3
(function() {

  HN.Utils.NewsParser = (function() {

    function NewsParser() {}

    NewsParser.parse = function(content) {
      var id, item, news, _i, _len, _ref;
      news = [];
      _ref = this.extract_news(content);
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        item = _ref[_i];
        if ($(item[1]).find("td:nth-child(2) > a:nth-child(3)").attr("href") == null) {
          id = parseInt($(item[0]).find("td:nth-child(3) > a").attr("href").replace("item?id=", ""));
        } else {
          id = parseInt($(item[1]).find("td:nth-child(2) > a:nth-child(3)").attr("href").replace("item?id=", ""));
        }
        news.push({
          id: id,
          link: $(item[0]).find("td:nth-child(3) > a").attr("href"),
          title: $(item[0]).find("td:nth-child(3) > a").html(),
          domain: this.get_domain($(item[0]).find("td:nth-child(3) > span").html()),
          points: parseInt($(item[1]).find("td:nth-child(2) > span").html()),
          user: $(item[1]).find("td:nth-child(2) > a:nth-child(2)").html(),
          discussion_link: $(item[1]).find("td:nth-child(2) > a:nth-child(3)").attr("href"),
          comments_counter: this.get_comments_count($(item[1]).find("td:nth-child(2) > a:nth-child(3)").html())
        });
      }
      return news;
    };

    NewsParser.extract_news = function(content) {
      var jobs_page_delim, news, news_counter, news_delim, page_delim, tr, trs, _i, _len;
      news_delim = 'height:5px';
      page_delim = 'height:10px';
      jobs_page_delim = 'height:45px';
      news_counter = 0;
      trs = $(content).find("center > table > tbody > tr:nth-child(3) > td > table tr");
      news = [];
      for (_i = 0, _len = trs.length; _i < _len; _i++) {
        tr = trs[_i];
        if ($(tr).attr("style") === news_delim) {
          news_counter += 1;
        } else if (($(tr).attr("style") === page_delim) || ($(tr).attr("style") === jobs_page_delim)) {
          break;
        } else {
          news[news_counter] || (news[news_counter] = []);
          news[news_counter].push(tr);
        }
      }
      return news;
    };

    NewsParser.get_comments_count = function(string) {
      if (isNaN(parseInt(string))) {
        return 0;
      } else {
        return parseInt(string);
      }
    };

    NewsParser.get_domain = function(string) {
      if (string !== null) {
        return string.replace(/^ \(/, "").replace(/\) $/, "");
      } else {
        return "";
      }
    };

    return NewsParser;

  })();

}).call(this);
