// Generated by CoffeeScript 1.3.3
(function() {

  HN.Utils.UserParser = (function() {

    function UserParser() {}

    UserParser.parse = function(content) {
      var item, key, user, value, _i, _len, _ref;
      user = {};
      _ref = this.extract_attributes(content);
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        item = _ref[_i];
        key = $(item).find("td:nth-child(1)").text().replace(":", "");
        value = $(item).find("td:nth-child(2)").html();
        if (key) {
          console.log(key, value);
          user[key] = value;
        }
      }
      return user;
    };

    UserParser.extract_attributes = function(content) {
      return $(content).find("center > table > tbody > tr:nth-child(3) > td > form > table > tbody > tr");
    };

    return UserParser;

  })();

}).call(this);
