// Generated by CoffeeScript 1.3.3
(function() {

  HN.Utils.click_or_tap = function(obj) {
    var new_obj, property, _i, _len;
    new_obj = {};
    for (_i = 0, _len = obj.length; _i < _len; _i++) {
      property = obj[_i];
      if (obj.hasOwnProperty(property)) {
        if (forge.is.mobile()) {
          new_obj["tap " + property] = obj[property];
        } else {
          new_obj["click " + property] = obj[property];
        }
      }
    }
    return new_obj;
  };

}).call(this);
