// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  HN.Views.Comment = (function(_super) {

    __extends(Comment, _super);

    function Comment() {
      return Comment.__super__.constructor.apply(this, arguments);
    }

    Comment.prototype.template = _.template($('#discussion-comment').html());

    Comment.prototype.template_menu = _.template($('#discussion-comment-menu').html());

    Comment.prototype.events = {
      'longTap': "toggle_menu"
    };

    Comment.prototype.render = function() {
      this.$el.append(this.template_menu(this.model.toJSON()));
      this.$el.append(this.template(this.model.toJSON()));
      this.$el.find("ul.menu").hide();
      return this;
    };

    Comment.prototype.open = function() {
      return HN.router.navigate("post/" + this.model.id, true);
    };

    Comment.prototype.toggle_menu = function() {
      return this.$el.find("ul.menu").toggle();
    };

    return Comment;

  })(Backbone.View);

}).call(this);
