// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  HN.Views.PostRow = (function(_super) {

    __extends(PostRow, _super);

    function PostRow() {
      return PostRow.__super__.constructor.apply(this, arguments);
    }

    PostRow.prototype.className = "post-row";

    PostRow.prototype.template = _.template($('#post-row').html());

    PostRow.prototype.template_commands = _.template($('#post-row-commands').html());

    PostRow.prototype.events = {
      "click div.post": "open",
      'longTap': "toggle_menu",
      'click li.user': 'show_user'
    };

    PostRow.prototype.render = function() {
      this.$el.append(this.template(this.model.toJSON()));
      this.$el.append(this.template_commands(this.model.toJSON()));
      this.$el.find("ul.menu").hide();
      return this;
    };

    PostRow.prototype.open = function() {
      if (this.model.id) {
        return HN.router.navigate("post/" + this.model.id, true);
      } else {
        return forge.tabs.open(this.model.get("link"));
      }
    };

    PostRow.prototype.toggle_menu = function() {
      return this.$el.find("ul.menu").toggle();
    };

    PostRow.prototype.show_user = function() {
      return HN.router.navigate("user/" + this.model.get("user"), true);
    };

    return PostRow;

  })(Backbone.View);

}).call(this);
