// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  HN.Views.User = (function(_super) {

    __extends(User, _super);

    function User() {
      return User.__super__.constructor.apply(this, arguments);
    }

    User.prototype.template = _.template($('#user').html());

    User.prototype.initialize = function() {
      _.bindAll(this, "render");
      this.model.on("change", this.render);
      return this.model.fetch();
    };

    User.prototype.render = function() {
      this.$el.html(this.template(this.model.toJSON()));
      return this;
    };

    return User;

  })(HN.Views.Page);

}).call(this);
