// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  HN.Models.Discussion = (function(_super) {

    __extends(Discussion, _super);

    function Discussion() {
      return Discussion.__super__.constructor.apply(this, arguments);
    }

    Discussion.prototype.initialize = function(attributes) {
      return this.url = "http://news.ycombinator.com/item?id=" + attributes.id;
    };

    Discussion.prototype.parse = function(response) {
      return HN.Utils.DiscussionParser.parse(response);
    };

    return Discussion;

  })(Backbone.Model);

}).call(this);
