// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  HN.Models.Discussion = (function(_super) {

    __extends(Discussion, _super);

    function Discussion() {
      return Discussion.__super__.constructor.apply(this, arguments);
    }

    Discussion.prototype.initialize = function(attributes) {
      return this.url = "http://news.ycombinator.com/item?id=" + attributes.id;
    };

    Discussion.prototype.parse = function(response) {
      return HN.Utils.DiscussionParser.parse(response);
    };

    Discussion.prototype.comments = function() {
      var comment, _i, _len, _ref, _results;
      _ref = this.get("comments");
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        comment = _ref[_i];
        _results.push(new HN.Models.Comment(comment));
      }
      return _results;
    };

    return Discussion;

  })(Backbone.Model);

}).call(this);
