// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  HN.Collections.Ask = (function(_super) {

    __extends(Ask, _super);

    function Ask() {
      return Ask.__super__.constructor.apply(this, arguments);
    }

    Ask.prototype.model = HN.Models.Post;

    Ask.prototype.url = "http://news.ycombinator.com/ask";

    Ask.prototype.parse = function(response) {
      return HN.Utils.NewsParser.parse(response);
    };

    return Ask;

  })(Backbone.Collection);

}).call(this);
